
export const ANIMATION_CONFIG = {
    player: {
        idle: {
            frameCount: 8,
            path: 'assets/animations/idle/idle',
            filePrefix: 'idle',
            extension: '.png',
            frameDuration: 10,
            loop: true,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        walk: {
            frameCount: 8,
            path: 'assets/animations/walk/walk',
            filePrefix: 'walk',
            extension: '.png',
            frameDuration: 8,
            loop: true,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        jump: {
            frameCount: 5,
            path: 'assets/animations/jump/jump',
            filePrefix: 'jump',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        lightPunch: {
            frameCount: 3,
            path: 'assets/animations/lightPunch/lightPunch',
            filePrefix: 'lightPunch',
            extension: '.png',
            frameDuration: 6,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 65, height: 100 },
        },
        airPunch: {
            frameCount: 2,
            path: 'assets/animations/airPunch/airPunch',
            filePrefix: 'airPunch',
            extension: '.png',
            frameDuration: 6,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 65, height: 100 },
        },
        hit: {
            frameCount: 4,
            path: 'assets/animations/hit/hit',
            filePrefix: 'hit',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 50, height: 100 },
        },
        block: {
            frameCount: 3,
            path: 'assets/animations/block/block',
            filePrefix: 'block',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        blockHit: {
            frameCount: 1,
            path: 'assets/animations/blockHit/blockHit',
            filePrefix: 'blockHit',
            extension: '.png',
            frameDuration: 6,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 50, height: 100 },
        },
        ko: {
            frameCount: 10,
            path: 'assets/animations/ko/ko',
            filePrefix: 'ko',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 85, offsetY: 230, width: 100, height: 50 },
        },
    },
    enemy: {
        idle: {
            frameCount: 8,
            path: 'assets/animations/idle/idle',
            filePrefix: 'idle',
            extension: '.png',
            frameDuration: 10,
            loop: true,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        walk: {
            frameCount: 8,
            path: 'assets/animations/walk/walk',
            filePrefix: 'walk',
            extension: '.png',
            frameDuration: 8,
            loop: true,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        jump: {
            frameCount: 5,
            path: 'assets/animations/jump/jump',
            filePrefix: 'jump',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        lightPunch: {
            frameCount: 3,
            path: 'assets/animations/lightPunch/lightPunch',
            filePrefix: 'lightPunch',
            extension: '.png',
            frameDuration: 6,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 65, height: 100 },
        },
        airPunch: {
            frameCount: 2,
            path: 'assets/animations/airPunch/airPunch',
            filePrefix: 'airPunch',
            extension: '.png',
            frameDuration: 6,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 65, height: 100 },
        },
        hit: {
            frameCount: 4,
            path: 'assets/animations/hit/hit',
            filePrefix: 'hit',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        block: {
            frameCount: 1,
            path: 'assets/animations/block/block',
            filePrefix: 'block',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        blockHit: {
            frameCount: 1,
            path: 'assets/animations/blockHit/blockHit',
            filePrefix: 'blockHit',
            extension: '.png',
            frameDuration: 6,
            loop: false,
            hurtbox: { offsetX: 100, offsetY: 180, width: 55, height: 100 },
        },
        ko: {
            frameCount: 10,
            path: 'assets/animations/ko/ko',
            filePrefix: 'ko',
            extension: '.png',
            frameDuration: 10,
            loop: false,
            hurtbox: { offsetX: 85, offsetY: 180, width: 55, height: 100 },
        },
    }
};
